name: Docker Compose CI

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "abcsy" --password-stdin
        # docker image build -t dab8106/pyflask:latest .
        # docker push dab8106/pyflask:latest
        docker compose up -d
        docker compose push
