name: Docker Compose CI

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          -
            # name: Set up Docker Build
            name: Compose Docker Buildx
            # uses: docker/setup-buildx-action@v3
            run: docker-compose up
          -
            name: Login to DockerHub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USER }}
              password: ${{ secrets.DOCKERHUB_PASS }}
          -
            name: Build and push
            run: docker-compose push
