name: Docker Compose CI

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
          -
            # name: Set up Docker Buildx
            # uses: docker/setup-buildx-action@v1
            name: Compose Docker Buildx
            run: docker-compose up
          -
            name: Login to DockerHub
            uses: docker/login-action@v1 
            with:
              username: ${{ secrets.DOCKERHUB_USER }}
              password: ${{ secrets.DOCKERHUB_PASS }}
          -
            name: Build and push
            run: docker-compose push
